baseurl = "http://davidyoung.io/"
languageCode = "en-us"
# title = "code monkey / photographer / dragon boater"
title = "David Young"
# Copyright notice. This is displayer in the footer.
copyright = "&copy; David Young. All rights reserved."

[params]
    # Social accounts. Link to these accounts are displayed in the header and
    # footer.
    twitter = "davidyoung604"
    github = "davidyoung604"
    linkedin = "davidyoung604"
    instagram = "davidyoung604"
    # googleplus = "Your Google+ user id"
    # facebook = "Your Facebook username"
    # stackoverflow = "Your Stackoverflow user id (number)"
    # Google Analytics API key.
    # ga_api_key = "Your Google Analytics tracking id"
    # Mixpanel API key.
    # mixpanel_api_key = "Your Mixpanel API key"
    author = "David"
    avatar = "/images/avatar.jpg"
    # contact = "Your contact link (ex. mailto:foo@example.com)"
    bio = "I'm just a guy with a proclivity for nerdy things and puns. I was the first one to realize that \"Carpe Diem\" is the original \"YOLO\"."
    # Short subtitle/tagline. This is displayed in the header.
    subtitle = "code monkey / photographer / dragon boater"
    themecolor = "#hexcolor" # Defines the tab color in Chrome for Android.
